import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { API } from '../context/AuthContext';
import { Download, TrendingUp } from 'lucide-react';

export default function TestResults() {
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    API.get('/test/results').then(r => setResults(r.data)).finally(() => setLoading(false));
  }, []);

  const exportPDF = (result) => {
    const content = `
CAREER GUIDANCE PLATFORM
Aptitude Test Report
=====================

Stream: ${result.stream}
Score: ${result.score}/${result.total} (${parseFloat(result.percentage).toFixed(1)}%)
Date: ${new Date(result.created_at).toLocaleDateString('en-IN')}
Career Recommendation: ${result.career_suggestion}

This report is generated by CareerGuide India
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aptitude_result_${result.stream}_${new Date(result.created_at).toLocaleDateString('en-IN').replace(/\//g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const scoreColor = (pct) => {
    const p = parseFloat(pct);
    if (p >= 70) return '#10b981';
    if (p >= 40) return '#f59e0b';
    return '#ef4444';
  };

  return (
    <div className="page-container">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '2rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 style={{ fontFamily: 'Syne, sans-serif', fontSize: '2rem', color: '#f8fafc' }}>Test Results</h1>
          <p style={{ color: '#64748b', marginTop: '0.5rem' }}>Your aptitude test history and performance</p>
        </div>
        <button className="btn-primary" onClick={() => navigate('/test')}>
          + Take New Test
        </button>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '4rem 0', color: '#475569' }}>Loading results...</div>
      ) : results.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '6rem 0' }}>
          <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>📝</div>
          <h2 style={{ fontFamily: 'Syne,sans-serif', color: '#f8fafc', marginBottom: '0.75rem' }}>No tests taken yet</h2>
          <p style={{ color: '#64748b', marginBottom: '2rem' }}>Take your first aptitude test to discover your ideal career path</p>
          <button className="btn-primary" onClick={() => navigate('/test')}>Take Aptitude Test</button>
        </div>
      ) : (
        <>
          {/* Summary stats */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '1rem', marginBottom: '2.5rem' }}>
            {[
              { label: 'Tests Taken', value: results.length },
              { label: 'Best Score', value: `${Math.max(...results.map(r => parseFloat(r.percentage))).toFixed(0)}%` },
              { label: 'Avg Score', value: `${(results.reduce((s, r) => s + parseFloat(r.percentage), 0) / results.length).toFixed(0)}%` },
              { label: 'Streams Tested', value: [...new Set(results.map(r => r.stream))].length },
            ].map(stat => (
              <div key={stat.label} className="card" style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.75rem', fontFamily: 'Syne,sans-serif', fontWeight: 800, color: '#f59e0b' }}>{stat.value}</div>
                <div style={{ fontSize: '0.78rem', color: '#64748b', marginTop: '0.25rem' }}>{stat.label}</div>
              </div>
            ))}
          </div>

          {/* Results list */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {results.map((result, i) => {
              const pct = parseFloat(result.percentage);
              const sc = scoreColor(pct);
              return (
                <div key={result.id} className="card">
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
                    <div style={{ flex: 1 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
                        <span style={{
                          background: 'rgba(59,130,246,0.1)', color: '#3b82f6',
                          fontSize: '0.8rem', fontWeight: 600, padding: '0.25rem 0.7rem', borderRadius: '100px'
                        }}>{result.stream}</span>
                        <span style={{ color: '#475569', fontSize: '0.8rem' }}>
                          {new Date(result.created_at).toLocaleDateString('en-IN', {
                            day: 'numeric', month: 'short', year: 'numeric'
                          })}
                        </span>
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '0.75rem' }}>
                        <div style={{ fontSize: '2rem', fontFamily: 'Syne,sans-serif', fontWeight: 800, color: sc }}>
                          {pct.toFixed(0)}%
                        </div>
                        <div>
                          <div style={{ color: '#94a3b8', fontSize: '0.875rem' }}>{result.score}/{result.total} correct</div>
                          <div style={{
                            fontSize: '0.78rem', fontWeight: 600, color: sc
                          }}>
                            {pct >= 80 ? 'Excellent' : pct >= 60 ? 'Good' : pct >= 40 ? 'Average' : 'Needs Improvement'}
                          </div>
                        </div>
                      </div>
                      {/* Progress bar */}
                      <div style={{ background: '#1e293b', borderRadius: '100px', height: '6px', marginBottom: '0.75rem', maxWidth: '300px' }}>
                        <div style={{
                          height: '100%', borderRadius: '100px', background: sc,
                          width: `${pct}%`, transition: 'width 0.6s ease'
                        }} />
                      </div>
                      {result.career_suggestion && (
                        <div style={{
                          display: 'inline-flex', alignItems: 'center', gap: '0.4rem',
                          background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.15)',
                          padding: '0.35rem 0.85rem', borderRadius: '8px'
                        }}>
                          <TrendingUp size={13} color="#f59e0b" />
                          <span style={{ color: '#f59e0b', fontSize: '0.8rem', fontWeight: 500 }}>{result.career_suggestion}</span>
                        </div>
                      )}
                    </div>
                    <button onClick={() => exportPDF(result)} style={{
                      display: 'flex', alignItems: 'center', gap: '0.4rem',
                      background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.2)',
                      color: '#10b981', padding: '0.5rem 0.9rem', borderRadius: '8px',
                      cursor: 'pointer', fontSize: '0.8rem', fontWeight: 500,
                      fontFamily: 'Space Grotesk, sans-serif', whiteSpace: 'nowrap'
                    }}>
                      <Download size={14} /> Export Report
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
